name: basic
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ">=3.0.0 <4.0.0" # Ensure it matches your Dart version

# Add regular dependencies here.
dependencies:
  rohd: ^0.3.1 # Use the latest version available

dev_dependencies:
  lints: ^2.0.0 # Ensure compatibility with the Dart SDK
  test: ^1.24.0