#include "Vdesign.h" // Generated by Verilator
#include "verilated.h"

int main(int argc, char** argv) {
    Verilated::commandArgs(argc, argv);
    Vdesign* top = new Vdesign;

    // Set inputs
    top->a = 1;
    top->b = 1;

    // Evaluate the design
    top->eval();

    // Print the output
    printf("Output y: %d\n", top->y);

    // Cleanup
    delete top;
    return 0;
}
